# Generated by Django 5.1.6 on 2025-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_card', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
